config/routes.rb
ClassLabs::Application.routes.draw do
  resources :users do
    member do
    get 'set_status'
    end
  end

  resources :tasks

  resources :labs

end

app/models/enlistment.rb
class Enlistment < ActiveRecord::Base
  attr_accessible :lab_id, :user_id
  belongs_to :lab
  belongs_to :user
end

app/models/lab.rb
class Lab < ActiveRecord::Base
  attr_accessible :name
  has_many :tasks
  has_many :enlistments
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description, :lab_id

  belongs_to :lab
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :name, :status
  has_many :enlistments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController
  # GET /labs
  # GET /labs.json
  def index
    @labs = Lab.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @labs }
    end
  end

  # GET /labs/1
  # GET /labs/1.json
  def show
    @lab = Lab.find(params[:id])
    @tasks = @lab.tasks
    @task = Task.new
    @enlistments = @lab.enlistments
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lab }
    end
  end

  # GET /labs/new
  # GET /labs/new.json
  def new
    @lab = Lab.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lab }
    end
  end

  # GET /labs/1
  def edit
    @lab = Lab.find(params[:id])
  end

  # POST /labs
  # POST /labs.json
  def create
    @lab = Lab.new(params[:lab])

    respond_to do |format|
      if @lab.save
        format.html { redirect_to @lab, notice: 'Lab was successfully created.' }
        format.json { render json: @lab, status: :created, location: @lab }
      else
        format.html { render action: "new" }
        format.json { render json: @lab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /labs/1
  # PUT /labs/1.json
  def update
    @lab = Lab.find(params[:id])

    respond_to do |format|
      if @lab.update_attributes(params[:lab])
        format.html { redirect_to @lab, notice: 'Lab was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labs/1
  # DELETE /labs/1.json
  def destroy
    @lab = Lab.find(params[:id])
    @lab.destroy

    respond_to do |format|
      format.html { redirect_to labs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.js
        format.html { redirect_to @task.lab, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_status
    @user = User.find(params[:id])
    @user.status = params[:status]
    @lab = Lab.find(params[:lab_id])
    respond_to do |format|
      if @user.save
        format.html { redirect_to lab_path(params[:lab_id]), notice: 'Status updated' }
        format.js
      else
        format.html { redirect_to lab_path(params[:lab_id]), notice: 'error updating status' }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/labs/_form.html.erb
<%= form_for(@lab) do |f| %>
  <% if @lab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lab.errors.count, "error") %> prohibited this lab from being saved:</h2>

      <ul>
      <% @lab.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/labs/edit.html.erb
<h1>Editing lab</h1>

<%= render 'form' %>

<%= link_to 'Show', @lab %> |
<%= link_to 'Back', labs_path %>

app/views/labs/index.html.erb
<h1>Listing labs</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @labs.each do |lab| %>
  <tr>
    <td><%= lab.name %></td>
    <td><%= link_to 'Show', lab %></td>
    <td><%= link_to 'Edit', edit_lab_path(lab) %></td>
    <td><%= link_to 'Destroy', lab, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lab', new_lab_path %>

app/views/labs/new.html.erb
<h1>New lab</h1>

<%= render 'form' %>

<%= link_to 'Back', labs_path %>

app/views/labs/show.html.erb
<p id="notice"><%= notice %></p>
<div>
  <p>
    <b>Name:</b>
    <%= @lab.name %>
  </p>

  <ul id="tasks">
    <% @tasks.each do |task| %>
      <li><%= task.description %></li>
    <% end %>
  </ul>

  <%= form_for(Task.new, remote: true) do |f| %>
      <%= f.hidden_field :lab_id, value: @lab.id %>

    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>
<div>
  <h2>class list</h2>
  <ul>
    <% @enlistments.each do |enlistment| %>
      <li id="<%= enlistment.user.name %>">
        <%= enlistment.user.name %>
        <% if enlistment.user.status == "red_light" %>
          <%= link_to(link_to("good to go", set_status_user_path(enlistment.user.id, status: "green_light", lab_id: enlistment.lab.id), remote: true)) %>
          <%= image_tag('red_dot.png', size: "16x16") %>
        <% elsif enlistment.user.status == "green_light" %>
          <%= link_to("help!", set_status_user_path(enlistment.user.id, status: "red_light", lab_id: enlistment.lab.id ), remote: true) %>
        <% end %>
      </li>
    <% end %>
  </ul>

</div>



<%= link_to 'Edit', edit_lab_path(@lab) %> |
<%= link_to 'Back', labs_path %>

<%= subscribe_to "/tasks/new" %>
<%= subscribe_to "/status/update" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClassLabs</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @lab  %>
    <%= f.hidden_field :lab_id, value: @lab.id %>
  <% end %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/create.js.erb
<% publish_to '/tasks/new' do %>
  $("#tasks").append("<li><%= j(@task.description) %></li>");
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.description %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_status.html.erb
<li id="<%= @user.name %>">
  <%= @user.name %>
  <% if @user.status == "red_light" %>
    <%= link_to("good to go", set_status_user_path(@user.id, status: "green_light", lab_id: @lab.id), remote: true) %>
    <%= image_tag('red_dot.png', size: "16x16") %>
  <% elsif @user.status == "green_light" %>
    <%= link_to("help!", set_status_user_path(@user.id, status: "red_light", lab_id: @lab.id), remote: true) %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password digest</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.password_digest %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/set_status.js.erb
<% publish_to '/status/update' do %>
  $("#<%= @user.name  %>").replaceWith("<%= j(render('status')) %>");
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>